### ISSUE TITLE
handling redirect links

### ISSUE THREAD

**Issue by lephong** [wikilinks/sift#11]
I was wondering how sift handles redirect links. For example, I have two wiki articles X and Y. Y redirects to X:
```
<page> 
<title> X </title>
<text> X is a ... </text>
</page>
```
and 
```
<page>
<title> Y </title>
<redirect title> X </redirect>
</page>
```
Then in another wiki article there's a mention to Y, e.g. 
`... this is [[Y]]  which is ...`

Can sift replace `[[Y]]` above by `[[X]]`? 
I found 
```
class WikipediaArticles(ModelBuilder, Documents):
    """ Prepare a corpus of documents from wikipedia """
    def build(self, corpus, redirects=None):
        ...
        if redirects:
```
Calling `build` with not-None redirects will do what I asked above. Am I right?

**Comment by andychisholm** [comment]
That's correct. There's a WikipediaRedirects model that pulls all of the redirects from Wikipedia and remaps links if you pass it in.

E.g. we do this at the top of the [example notebook](https://github.com/wikilinks/sift/blob/master/sift.ipynb):
```
redirects = wikipedia.WikipediaRedirects()(corpus)
docs = wikipedia.WikipediaArticles()(corpus, redirects)
```

**Comment by lephong** [comment]
Great. Thanks a lot.
