### ISSUE TITLE
Dump directory

### ISSUE THREAD

**Issue by userofgithub1** [wikilinks/sift#13]
Hello Andy,

I'm trying to build entities models. I downloaded the 2011 wikiepedia dump (I need to use this one and not the latest). And when I run `wikipedia_corpus = wikipedia.WikipediaCorpus()(sc, wikipedia_base_path)` I get this error
```
318                 raise Py4JJavaError(
    319                     "An error occurred while calling {0}{1}{2}.\n".
--> 320                     format(target_id, ".", name), value)
    321             else:
    322                 raise Py4JError(
```
```
Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.newAPIHadoopFile.
: org.apache.hadoop.mapreduce.lib.input.InvalidInputException:  Input path does not exist:
```

The dump is located on my desktop and not in the latest directory, is that the cause? If yes would you please give any guidance of how to move it to the latest directory?

I saw your command `download-wikipedia latest` but i really don't know how to use it and where, I'm a beginner with command lines.

Please any help will be much appreciated. Thank you so much Andy :)

**Comment by userofgithub1** [comment]
I know I'm asking for a lot but my work is fundamentally built on top of all this, of course all of this will be cited :). So, it would be really appreciated and useful if you can show a very simple example of how to generate an output of CoNLL evaluation by NEL for analysis with conll03_nel_eval since I saw in your paper you tested on both Conll and TAC14. 

Many many thanks Andy,

**Comment by andychisholm** [comment]
Hey @userofgithub1 regarding the dump directory, it's a little tricky to help without knowing what the local filesystem looks like. All I can suggest is that you set `wikipedia_base_path` to the absolute path of the directory containing the dump files on your system.

Regarding the generation of conll-eval linker output, that's more of a `nel` question. After building the models, I would suggest following the [sample notebook](https://github.com/wikilinks/nel/blob/master/notebooks/train.ipynb) down to:
```python
from nel.harness.format import inject_markdown_links
```

In the same way we generate markdown output for display there, you can instead use a similar document output formatter for neleval, i.e. `nel.harness.format.to_neleval` (see [here](https://github.com/wikilinks/nel/blob/master/nel/harness/format.py#L202)).
```python
from nel.harness.format import to_neleval

to_neleval(linked_sample[0])
```

**Comment by userofgithub1** [comment]
Thank you Andrew. I resolved the issue of the directory, now dealing with some spark insanity. 

I’m trying to investigate other methods for the disambiguation part, other than the SVM rank. So, please bear with me. And any performance improvement even if I only obtain 1% improvement I will contact you and see if you wish to integrate it in your framework. I owe you :)

Two more questions that are related to NEL and conll_eval

NEL: Ok that’s for the conll output format. But instead of training and testing on wikipedia articles as shown in your example, how to train on conll-train partition and test on testb?

Conll_eval: How to evaluate the output of the NEL system with Ben Hachey's evaluation implementation? I saw they only mentioned command line example which is really unclear to me.


Thank you so much for your patience and fast reply,
