### ISSUE TITLE
idf and tfidf models 

### ISSUE THREAD

**Issue by userofgithub1** [wikilinks/sift#14]
Hey,

I'm trying to build idfs and tfidfs models but I cannot store them. I followed the examples and then to build the idfs model I did:
```
idfs_model = text\
    .TermIdfs()\
    .build(docs)\
    .map(text.TermIdfs.format_item)
```
and when I try to store it in a file by
 ```
data.ObjectStore\
    .Get('models:idfs[wikipedia]')\
    .save_many(idfs_model.collect())
```
 I get this error 
```
sift/models/text.py", line 167, in <lambda>
    .map(lambda (term, (df, rank)): (term, df))\
TypeError: 'int' object is not iterable
```

For building the tfidfs model I did:

```
vocab = text.TermVocab(max_rank=100000,min_rank=0,lowercase=True,min_df=5)(docs.sample(False, 0.25))
mentions = text.IndexMappedMentions(sentence_window=1,lowercase=True)(sc, docs, vocab)

tfidfs_model = text\
    .EntityMentionTermFrequency(max_ngram=1, normalize = True)\
    .build(mentions,idfs_model)\
    .map(text.EntityMentionTermFrequency.format_item)
```
when I try to store it by
 ```
data.ObjectStore\
    .Get('models:tfidfs[wikipedia]')\
    .save_many(tfidfs_model.collect())
```
I get this error:
`ValueError: cannot mmap an empty file`  caused by:

```
sift/models/text.py", line 186, in <lambda>
    m = mentions\
ValueError: too many values to unpack
```
How can i resolve these errors? Is there mistakes in my calls or is there something I should change in the lambda errors?

At the beggining I played around with spark configs but I dont think the problem is there since I succeeded to build the ce and enc models.

I'm using python 2.7. 

I'd really appreciate any help. 
Thank you in advance,

**Comment by userofgithub1** [comment]
Follow up, for anyone that might face the same issue. I solved it by editing ` .map(lambda (term, (df, rank)): (term, df))\` to  `.map(lambda (term, df): (term, df))\` (in this case, the entire line can be removed) since the output of `TermDocumentFrequencies` is:
```
[(u'fawn', 3),
 (u'1,800', 31),
 (u'clotted', 3),
 (u'comically', 11),
 (u'Adjusting', 3),
 (u'O(log', 6),
```
No `rank` is taken as an input. 

However, building tfidf model is still causing:

```
sift/models/text.py", line 186, in <lambda>
    m = mentions\
ValueError: too many values to unpack
```
Any hints regarding `EntityMentionTermFrequency` will be appreciated.

Best,

**Comment by userofgithub1** [comment]
I would like to post how the issue was resolved it might be helpful for others, since the issues are clearly just a result of multiple commits so I'm sure @andychisholm has a better and efficient solution.

`idfs` must be in the form of tuples and not dictionaries, so:
```
idfs= TermDocumentFrequencies().build(corpus)\
         .mapValues(lambda df: math.log(N/df))
```
Now `EntityMentionTermFrequency` does not receive `mentions` in the form of tuple of tuple like `(target, (span, text)): (target, text)` instead the first part of the build method in `EntityMentionTermFrequency` are changed to:
```
def build(self, mentions, idfs):
        log.info('edited')
        m = mentions\
            .map(lambda x: (x["_id"], x["text"])).groupByKey()\
            .map(lambda x: (x[0], list(x[1])))\
            .mapValues(lambda v: ngrams(" ".join(v), self.max_ngram))\
            .flatMap(lambda (target, tokens): (((target, t), 1) for t in tokens))\
```

Hope this is helpful for someone.
Best,

**Comment by arunzz** [comment]
Thank you for posting this. I found this useful but I am getting an error. Can you pls help resolve.

THese two steps work but I get error in saving the model.

idfs= text.TermDocumentFrequencies().build(docs).mapValues(lambda df: math.log(N/df))
-----------------------works---------------------------
vocab = text.TermVocab(max_rank=100000,min_rank=0,lowercase=True,min_df=5)(docs.sample(False, 0.25))
mentions = text.IndexMappedMentions(sentence_window=1,lowercase=True)(sc, docs, vocab)

tfidfs_model = text\
    .EntityMentionTermFrequency(max_ngram=1, normalize = True)\
    .build(mentions,idfs)\
    .map(text.EntityMentionTermFrequency.format_item)
------------------------works---------------------------
data.ObjectStore\
    .Get('models:idfs[wikipedia]')\
    .save_many(idfs_model.collect())
----------------------------------works------------------------
data.ObjectStore\
   .Get('models:tfidfs[wikipedia]')\
   .save_many(tfidfs_model.collect())
--------------------fails----------------------- 
**Error**:
 File "/usr/local/lib/python2.7/dist-packages/sift/models/text.py", line 187, in <lambda>
    .mapValues(lambda v: ngrams(" ".join(v), self.max_ngram))\
TypeError: sequence item 0: expected string, list found

**This is the class updated in sift text.py as per the above comment.**
class EntityMentionTermFrequency(ModelBuilder, Model):
    """ Compute tf-idf weighted token counts over sentence contexts around links in a corpus """
    def __init__(self, max_ngram=1, normalize = True):
        self.max_ngram = max_ngram
        self.normalize = normalize


    def build(self, mentions, idfs):
        m = mentions\
	    .map(lambda x: (x["_id"], x["text"])).groupByKey()\
            .map(lambda x: (x[0], list(x[1])))\
            .mapValues(lambda v: ngrams(" ".join(v), self.max_ngram))\
            .flatMap(lambda (target, tokens): (((target, t), 1) for t in tokens))\
            .reduceByKey(add)\
            .map(lambda ((target, token), count): (token, (target, count)))\
            .leftOuterJoin(idfs)\
            .filter(lambda (token, ((target, count), idf)): idf != None)\
            .map(lambda (token, ((target, count), idf)): (target, (token, math.sqrt(count)*idf)))\
            .groupByKey()

        return m.mapValues(self.normalize_counts if self.normalize else list)

**Comment by arunzz** [comment]
Kindly pls let know of any help on this

**Comment by userofgithub1** [comment]
Hi,
Could you share the output format of this:

Mentions\.map(lambda x: (x["_id"], x["text"])).groupByKey()\
.map(lambda x: (x[0], list(x[1])))\
.collect()

**Comment by userofgithub1** [comment]
@arunzz  ngram method recieves a string. Simpley, make sure that the ngram call causing the error does actually convert the list to a string, which should be accomplished by the " ".join(v).

**Comment by woshiyyya** [comment]
@userofgithub1 I encountered the same problem as @arunzz . It seems that v[0] is a list. So could you please show your full code of training tfidf_model, which might help a lot. Thank you~

**Comment by userofgithub1** [comment]
Sure, full code is below. 

Could you please take a look at this issue it's regarding the offset calculations https://github.com/wikilinks/nel/issues/21 thanks :)
```
import math
import numpy
import ujson as json
from bisect import bisect_left, bisect_right
from operator import add, itemgetter
from collections import Counter

from sift.models.links import EntityVocab
from sift.dataset import ModelBuilder, Documents, Model, Mentions, IndexedMentions, Vocab
from sift.util import ngrams, iter_sent_spans, trim_link_subsection, trim_link_protocol

from sift import logging
log = logging.getLogger()

class TermFrequencies(ModelBuilder, Model):
    """ Get term frequencies over a corpus """
    def __init__(self, lowercase, max_ngram):
        self.lowercase = lowercase
        self.max_ngram = max_ngram

    def build(self, docs):
        m = docs.map(lambda d: d['text'])
        if self.lowercase:
            m = m.map(unicode.lower)

        return m\
            .flatMap(lambda text: ngrams(text, self.max_ngram))\
            .map(lambda t: (t, 1))\
            .reduceByKey(add)\
            .filter(lambda (k,v): v > 1)

    @staticmethod
    def format_item(self, (term, count)):
        return {
            '_id': term,
            'count': count,
        }

class EntityMentions(ModelBuilder, Mentions):
    """ Get aggregated sentence context around links in a corpus """
    def __init__(self, sentence_window = 1, lowercase=False, normalize_url=True, strict_sentences=True):
        self.sentence_window = sentence_window
        self.lowercase = lowercase
        self.strict_sentences = strict_sentences
        self.normalize_url = normalize_url

    @staticmethod
    def iter_mentions(doc, window = 1, norm_url=True, strict=True):
        sent_spans = list(iter_sent_spans(doc['text']))
        sent_offsets = [spns.start for spns in sent_spans]

        for link in doc['links']:
            # align the link span over sentence spans in the document
            # mention span may cross sentence bounds if sentence tokenisation is dodgy
            # if so, the entire span between bounding sentences will be used as context
            sent_start_idx = bisect_right(sent_offsets, link['start']) - 1
            sent_end_idx = bisect_left(sent_offsets, link['stop']) - 1

            lhs_offset = window / 2
            rhs_offset = (window - lhs_offset) - 1
            sent_start_idx = max(0, sent_start_idx - lhs_offset)
            sent_end_idx = min(len(sent_spans)-1, sent_end_idx + rhs_offset)
            sent_offset = sent_spans[sent_start_idx].start

            span = (link['start'] - sent_offset, link['stop'] - sent_offset)
            target = link['target']
            if norm_url:
                target = trim_link_subsection(link['target'])
                target = trim_link_protocol(target)
                
            mention = doc['text'][sent_spans[sent_start_idx].start:sent_spans[sent_end_idx].stop]

            # filter out instances where the mention span is the entire sentence
            if span == (0, len(mention)):
                continue

            if strict:
                # filter out list item sentences
                sm = mention.strip()
                if not sm or sm.startswith('*') or sm[-1] not in '.!?"\'':
                    continue
            
            yield target, doc['_id'], mention, span

    def build(self, docs):
        m = docs.flatMap(lambda d: self.iter_mentions(d, self.sentence_window, self.normalize_url, self.strict_sentences))
        if self.lowercase:
            m = m.map(lambda (t, src, m, spn): (t, src, m.lower(), spn))
        return m

class IndexMappedMentions(EntityMentions, IndexedMentions):
    """ Entity mention corpus with terms mapped to numeric indexes """
    def build(self, sc, docs, vocab):
        tv = sc.broadcast(dict(vocab.map(lambda r: (r['_id'], r['rank'])).collect()))
        return super(IndexMappedMentions, self)\
            .build(docs)\
            .map(lambda m: self.transform(m, tv))

    @staticmethod
    def transform((target, source, text, span), vocab):
        vocab = vocab.value

        start, stop = span
        pre = list(ngrams(text[:start], 1))
        ins = list(ngrams(text[start:stop], 1))
        post = list(ngrams(text[stop:], 1))
        indexes = [vocab.get(t, len(vocab)-1) for t in (pre+ins+post)]

        return target, source, indexes, (len(pre), len(pre)+len(ins))

class TermDocumentFrequencies(ModelBuilder):
    """ Get document frequencies for terms in a corpus """
    def __init__(self, lowercase=False, max_ngram=1, min_df=2):
        self.lowercase = lowercase
        self.max_ngram = max_ngram
        self.min_df = min_df

    def build(self, docs):
        m = docs.map(lambda d: d['text'])
        if self.lowercase:
            m = m.map(lambda text: text.lower())
        

        return m\
            .flatMap(lambda text: set(ngrams(text, self.max_ngram)))\
            .map(lambda t: (t, 1))\
            .reduceByKey(add)\
            .filter(lambda (k,v): v > self.min_df)

class TermVocab(TermDocumentFrequencies, Vocab):
    """ Generate unique indexes for termed based on their document frequency ranking. """
    def __init__(self, max_rank, min_rank=100, *args, **kwargs):
        self.max_rank = max_rank
        self.min_rank = min_rank
        super(TermVocab, self).__init__(*args, **kwargs)

    def build(self, docs):
        m = super(TermVocab, self)\
            .build(docs)\
            .map(lambda (t, df): (df, t))\
            .sortByKey(False)\
            .zipWithIndex()\
            .map(lambda ((df, t), idx): (t, (df, idx)))

        if self.min_rank != None:
            m = m.filter(lambda (t, (df, idx)): idx >= self.min_rank)
        if self.max_rank != None:
            m = m.filter(lambda (t, (df, idx)): idx < self.max_rank)
        return m

    @staticmethod
    def format_item((term, (f, idx))):
        return {
            '_id': term,
            'count': f,
            'rank': idx
        }

class TermIdfs(TermDocumentFrequencies, Model):
    """ Compute tf-idf weighted token counts over sentence contexts around links in a corpus """
    def build(self, corpus):
        log.info('Counting documents in corpus...')
        N = float(corpus.count())
        dfs = super(TermIdfs, self).build(corpus)
        
        log.info('Building idf model: N=%i', N)
        return dfs\
            .map(lambda (term, df): (term, df))\
            .mapValues(lambda df: math.log(N/df))


    @staticmethod
    def format_item((term, idf)):
        return {
            '_id': term,
            'idf': idf,
        }

class EntityMentionTermFrequency(ModelBuilder, Model):
    """ Compute tf-idf weighted token counts over sentence contexts around links in a corpus """
    def __init__(self, max_ngram=1, normalize = True):
        self.max_ngram = max_ngram
        self.normalize = normalize
    
    def build(self, mentions, idfs):
        log.info('edited')
        m = mentions\
            .map(lambda x: (x["_id"], x["text"])).groupByKey()\
            .map(lambda x: (x[0], list(x[1])))\
            .mapValues(lambda v: ngrams(" ".join(v), self.max_ngram))\
            .flatMap(lambda (target, tokens): (((target, t), 1) for t in tokens))\
            .reduceByKey(add)\
            .map(lambda ((target, token), count): (token, (target, count)))\
            .leftOuterJoin(idfs)\
            .filter(lambda (token, ((target, count), idf)): idf != None)\
            .map(lambda (token, ((target, count), idf)): (target, (token, math.sqrt(count)*idf)))\
            .groupByKey()
        return m.mapValues(self.normalize_counts if self.normalize else list)

    @staticmethod
    def normalize_counts(counts):
        norm = numpy.linalg.norm([v for _, v in counts])
        return [(k, v/norm) for k, v in counts]

    @staticmethod
    def format_item((link, counts)):
        return {
            '_id': link,
            'counts': dict(counts),
        }

```

**Comment by woshiyyya** [comment]
Thanks！ But there are still problem. I print out a middle value of m
```python
m = mentions\  
    .map(lambda x: (x["_id"], x["text"])).groupByKey()\     
    .map(lambda x: (x[0], list(x[1])))    
print m.take(1)
```
which is
`
[(u'en.wikipedia.org/wiki/Goritsky_Monastery_(Pereslavl-Zalessky)', [[0, 99999, 4871, 3, 457, 99999, 6238, 8, 2, 1131, 4434, 4871, 1, 99999, 1343]])]
`  

I can't figure out what this part mean.
```python
.mapValues(lambda v: ngrams(" ".join(v), self.max_ngram))\
```

**Comment by userofgithub1** [comment]
Could you share the error message? If there is no error message, could you share the final output of the model?

Best,

**Comment by woshiyyya** [comment]
oh, it is like this:
```
File "/usr/local/lib/python2.7/dist-packages/sift/models/text.py", line 187, in 
.mapValues(lambda v: ngrams(" ".join(v), self.max_ngram))
TypeError: sequence item 0: expected string, list found
```

**Comment by userofgithub1** [comment]
Your output should look like this after print
.map(lambda x: (x[0], list(x[1]))):

[(u'en.wikipedia.org/wiki/Dru_Drury', [((20, 29), u'It was described by Dru Drury in 1770.'), ((20, 29, 2), u'It was described by Dru Drury in 1770.2')]), (u'en.wikipedia.org/wiki/Cerambycidae', [((61, 73), u'"Plinthocoelium virens" is a species of beetle in the family Cerambycidae.')])]

The line your asking about, sends the joined strings to the ngram method. 

Hope this is helpful :)

**Comment by basque21** [comment]
Hi, 
I'm trying to follow your steps, but I'm getting an error when initializing  `mentions` . When I do ` mentions = text.IndexMappedMentions(sentence_window=1,lowercase=True)(sc, docs, vocab)` I'm getting:

```
AttributeError                            Traceback (most recent call last)
<ipython-input-13-e8a4ec6995b7> in <module>
----> 1 mentions = text.IndexMappedMentions(sentence_window=1,lowercase=True)(sc, docs, vocab)
      2 

/var/lib/spark/tmp/spark-7e3c1a98-7e9a-40b5-9d8f-ff01ef93065e/userFiles-ed742db8-39c1-4a20-9871-8f87c7c11075/sift.zip/sift/dataset.py in __call__(self, *args, **kwargs)
      5 
      6     def __call__(self, *args, **kwargs):
----> 7         return self.build(*args, **kwargs).map(self.format_item)
      8 
      9     def build(self, *args, **kwargs):

/var/lib/spark/tmp/spark-7e3c1a98-7e9a-40b5-9d8f-ff01ef93065e/userFiles-ed742db8-39c1-4a20-9871-8f87c7c11075/sift.zip/sift/models/text.py in build(self, sc, docs, vocab)
     93         tv = sc.broadcast(dict(vocab.map(lambda r: (r['_id'], r['rank'])).collect()))
     94         return super(IndexMappedMentions, self)\
---> 95             .build(docs)\
     96             .map(lambda m: self.transform(m, tv))
     97 

AttributeError: 'NoneType' object has no attribute 'map'
```

Could anyone help me, please?

Thanks

**Comment by iuria21** [comment]
Hi, I'm dealing with the same error. My output is the same as @woshiyyya and @arunzz , how can I do it to get this output @userofgithub1 ?

If I need this output I suppouse that I need to change the `IndexMappedMentions` to return `return new_target, source, text, (len(pre), len(pre)+len(ins))` with `text` instead of `indexes`?

And, in any case, if the output is of format `[(u'en.wikipedia.org/wiki/Dru_Drury', [((20, 29), u'It was described by Dru Drury in 1770.'), ((20, 29, 2), u'It was described by Dru Drury in 1770.2')]), (u'en.wikipedia.org/wiki/Cerambycidae', [((61, 73), u'"Plinthocoelium virens" is a species of beetle in the family Cerambycidae.')])]` the line `.mapValues(lambda v: ngrams(" ".join(v), self.max_ngram))\` it's raising an other error for me.

Please, I would really appreciate your answer,
Thanks
