### ISSUE TITLE
No command 'sift'

### ISSUE THREAD

**Issue by saurabhbh21** [wikilinks/sift#16]
After downloading Wikipedia data using the command, '**download-wikipedia latest**'. When I execute **sift build-corpus --save redirects WikipediaRedirects latest json**, I'm getting the error **_No command 'shift'_.**

**Comment by user144amal** [comment]
That seems to be broken. You can go to
https://dumps.wikimedia.org/enwiki/ and download the "pages-articles"
manually.

**Comment by saurabhbh21** [comment]
The issue is not with downloading articles, but with build-corpus code. The page articles are downloaded in xml format.

**Comment by user144amal** [comment]
Sorry, I misunderstood your issue. Did you try to follow this example https://github.com/wikilinks/sift/blob/master/sift.ipynb ?

**Comment by saurabhbh21** [comment]
I want to use sift for nel, not sure how this notebook be helpful, any doc.

**Comment by user144amal** [comment]
This will help: https://github.com/wikilinks/nel/blob/master/notebooks/train.ipynb

**Comment by saurabhbh21** [comment]
Thanx a lot. I think I'm good to proceed now.

**Comment by andychisholm** [comment]
Thanks @user144amal, that's correct. The command-line interface has been deprecated in favour of the API and the notebook is indeed the best guide for that.
